apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: prometheus
spec:
  selector:
    app: prometheus-prometheus-oper-operator
    name: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer